# :schema node_modules/wrangler/config-schema.json
name = "ihka-jabar"
compatibility_date = "2024-07-29"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "ihka-jabar"
database_id = "ee5f9254-aef2-4a3e-a841-14a06c76bc38"
migrations_dir = "./drizzle"

[[kv_namespaces]]
binding = "ihka-jabar-kv"
id = "551e65c3dfed4cdea80d2c44c6c6d03e"