name = "ihka-jabar"
compatibility_date = "2024-07-29"
compatibility_flags = [ 'nodejs_compat' ]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "ihka_jabar_v2"
database_name = "ihka-jabar-v2"
database_id = "f641cbe5-88e5-4b38-91a6-b5ab6112d42e"
migrations_dir = "./drizzle"

[[kv_namespaces]]
binding = "ihka-jabar-kv"
id = "551e65c3dfed4cdea80d2c44c6c6d03e"
